import { NavigationBar } from './shared/ui/index.js'
import logo from './assets/navigation/logo.svg'
import homeIcon from './assets/navigation/home.svg'
import groupFeedIcon from './assets/navigation/group-feed.svg'
import networkingIcon from './assets/navigation/networking.svg'
import mypageIcon from './assets/navigation/mypage.svg'
const navItems=[{label:'홈',href:'/',icon:<img src={homeIcon} alt=""/>,isActive:true},{label:'모임 피드',href:'/groups',icon:<img src={groupFeedIcon} alt=""/>},{label:'네트워킹',href:'/networking',icon:<img src={networkingIcon} alt=""/>},{label:'마이 페이지',href:'/mypage',icon:<img src={mypageIcon} alt=""/>}]
const members=['연세대 외 2명','서강대 외 3명','홍익대 외 3명']
const Arrow=()=> <span className="text-3xl font-light text-[#858485]">›</span>
function Card({title,children}){return <section className="rounded-[20px] border border-[#F4F4F4] bg-white px-10 py-5"><header className="mb-6 flex justify-between"><h2 className="text-xl font-bold">{title}</h2><button aria-label={title+' 더 보기'}><Arrow/></button></header>{children}</section>}
function Row({member,event=false}){return <article className="flex items-center gap-6 border-b border-[#F4F4F4] py-3 last:border-0"><div className="size-[60px] shrink-0 rounded-2xl bg-[#DBBEA6]"/><div className="flex-1">{event&&<span className="mr-1 rounded-full bg-[#F8F2ED] px-4 py-1 text-xs text-[#7D5C42]">커피챗</span>}<b className="text-sm">Spring boot 스터디</b><p className="mt-2 text-xs text-[#858485]">프로젝트 | {member}</p></div><button className="rounded-lg bg-[#7D5C42] px-5 py-2 text-sm text-white">참여하기</button></article>}
function App(){return <div className="min-h-screen bg-white text-[#171617]"><NavigationBar brand={<img className="size-full object-contain" src={logo} alt="신촌링크"/>} items={navItems}/><main className="ml-[300px] min-h-screen px-6 py-10"><div className="mx-auto flex max-w-[1157px] flex-col gap-10"><header><h1 className="text-[28px] font-bold">신촌 님, 안녕하세요 !</h1><p className="mt-4 text-lg text-[#A2A2A2]">신촌톤에서 성장 가능한 연결을 만나보세요.</p></header><div className="grid grid-cols-[506px_1fr] gap-4"><Card title="내 프로필"><div className="flex gap-6"><div className="size-[134px] shrink-0 rounded-full bg-[#DBBEA6]"/><div><b className="text-lg">김신촌</b><span className="ml-2 rounded-full bg-[#F8F2ED] px-4 py-1 text-xs text-[#7D5C42]">홍익대학교</span><p className="mt-4 text-xs text-[#858485]">시각 디자인과 | UXUI Designer</p><p className="mt-3 text-xs">Figma | Photoshop</p></div></div></Card><Card title="참가 중인 모임">{members.slice(0,2).map(x=><Row member={x} key={x}/>)}</Card></div><Card title="네트워킹"><div className="grid grid-cols-3 gap-8">{members.map(x=><div className="flex gap-5" key={x}><div className="size-[60px] shrink-0 rounded-full bg-[#DBBEA6]"/><div><b>김신촌</b><p className="mt-2 text-xs text-[#858485]">시각 디자인과 | UXUI Designer</p><p className="mt-2 text-xs">Figma | Photoshop</p></div></div>)}</div></Card><Card title="추천 모임">{members.map(x=><Row member={x} key={x}/>)}</Card><Card title="네트워킹 행사">{members.map(x=><Row event member={x} key={x}/>)}</Card><Card title="추천 채용 공고"><div className="grid grid-cols-4 gap-9">{[1,2,3,4].map(x=><article key={x}><div className="aspect-square rounded-2xl bg-[#DBBEA6]"/><b className="mt-3 block text-sm">Backend Developer</b><p className="mt-2 text-xs text-[#858485]">스타트업 코드잇 채용</p><div className="mt-2 flex gap-2 text-xs"><span className="rounded bg-[#7D5C42] px-3 py-1 text-white">서울</span><span className="rounded bg-[#DEDEDE] px-3 py-1">경력 무관</span><span className="rounded bg-[#F4F4F4] px-3 py-1">D-5</span></div></article>)}</div></Card></div></main></div>}
export default App
